---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

# Use "systemd-timesyncd" for time services. It's available by default.
harden_linux_ntp: "systemd-timesyncd"

# Password for user "root" and "vagrant" is "vagrant" in both cases. As
# "vagrant" user is available in every Vagrant Ubuntu Box just use it.
harden_linux_root_password: "$6$rounds=656000$mysecretsalt$fpyQ9hMON6iKKuM0Rz10WZKNJR4OkQTVfBmd4SPrJPsU9XmgQGRtogcUnFB5FLRIitswuQFr6Tr8Mos9l7Ojm0"
harden_linux_deploy_user: "vagrant"
harden_linux_deploy_user_password: "$6$rounds=656000$mysecretsalt$fpyQ9hMON6iKKuM0Rz10WZKNJR4OkQTVfBmd4SPrJPsU9XmgQGRtogcUnFB5FLRIitswuQFr6Tr8Mos9l7Ojm0"
harden_linux_deploy_user_home: "/home/vagrant"
harden_linux_deploy_user_uid: "1000"
harden_linux_deploy_user_shell: "/bin/bash"

# Enable IP forwarding for IPv4 and IPv6
harden_linux_sysctl_settings_user:
  "net.ipv4.ip_forward": 1
  "net.ipv6.conf.default.forwarding": 1
  "net.ipv6.conf.all.forwarding": 1

# Let SSHd listen on port 22, allow password authentication and allow "root"
# login. The last two settings are not recommended for production use but for
# this test deployment it's okay as it makes debugging easier and faster.
harden_linux_sshd_settings_user:
  "^Port ": "Port 22"
  "^PasswordAuthentication": "PasswordAuthentication yes"
  "^PermitRootLogin": "PermitRootLogin yes"

# Open a few ports for ssh, Wireguard, HTTP, HTTPS and SMTP.
harden_linux_ufw_rules:
  - rule: "allow"
    to_port: "22"
    protocol: "tcp"
  - rule: "allow"
    to_port: "51820"
    protocol: "udp"
  - rule: "allow"
    to_port: "80"
    protocol: "tcp"
  - rule: "allow"
    to_port: "443"
    protocol: "tcp"
  - rule: "allow"
    to_port: "25"
    protocol: "tcp"

# Allow all traffic from the following networks.
harden_linux_ufw_allow_networks:
  - "10.0.0.0/8"
  - "172.16.0.0/12"
  - "192.168.0.0/16"

# Enable logging for UFW.
harden_linux_ufw_logging: 'on'

# Set the default forward policy to "ACCEPT".
harden_linux_ufw_defaults_user:
  "^DEFAULT_FORWARD_POLICY": 'DEFAULT_FORWARD_POLICY="ACCEPT"'

# Don't block SSH logins from the following networks even login attempts fail
# for a few times.
harden_linux_sshguard_whitelist:
  - "127.0.0.0/8"
  - "::1/128"
  - "10.0.0.0/8"
  - "172.16.0.0/12"
  - "192.168.0.0/16"

# Directory where the etcd certificates are stored on the Ansible controller
# host. Certificate files for etcd will be copied from this directory to
# the etcd nodes.
etcd_ca_conf_directory: "{{ k8s_ca_conf_directory }}"
# Interface where the etcd service is listening on.
etcd_interface: "{{ k8s_interface }}"

# Interface where the Kubernetes control plane services are listening on.
k8s_interface: "wg0"

# Directory where the Kubernetes certificates are stored on the Ansible
# controller host.
k8s_ca_conf_directory: "/tmp/k8s-ca"
# Permissions for the Kubernetes CA directory.
k8s_ca_conf_directory_perm: "0700"
# Permissions for the Kubernetes CA files.
k8s_ca_file_perm: "0600"
# Owner of the Kubernetes CA files.
k8s_ca_certificate_owner: "vagrant"
# Group of the Kubernetes CA files.
k8s_ca_certificate_group: "vagrant"

# Common name for "etcd" certificate authority certificates.
ca_etcd_csr_cn: "etcd"
ca_etcd_csr_key_algo: "ecdsa"
ca_etcd_csr_key_size: "384"

# Common name for "kube-apiserver" certificate authority certificate.
ca_k8s_apiserver_csr_cn: "kubernetes"
ca_k8s_apiserver_csr_key_algo: "ecdsa"
ca_k8s_apiserver_csr_key_size: "384"

# Common name for "etcd" servers
etcd_server_csr_cn: "etcd-server"
etcd_server_csr_key_algo: "ecdsa"
etcd_server_csr_key_size: "384"

# Common name for "etcd" peers
etcd_peer_csr_cn: "etcd-peer"
etcd_peer_csr_key_algo: "ecdsa"
etcd_peer_csr_key_size: "384"

# Common name for "etcd" client certificates
etcd_client_csr_cn_prefix: "etcd-client"
etcd_client_csr_key_algo: "ecdsa"
etcd_client_csr_key_size: "384"

# Common name for "kube-apiserver"
k8s_apiserver_csr_cn: "k8s-apiserver"
k8s_apiserver_csr_key_algo: "ecdsa"
k8s_apiserver_csr_key_size: "384"

# Common name for Kubernetes "admin" user certificate (used by "kubectl" e.g)
k8s_admin_csr_cn: "k8s-admin"
k8s_admin_csr_key_algo: "ecdsa"
k8s_admin_csr_key_size: "384"

k8s_worker_csr_key_algo: "ecdsa"
k8s_worker_csr_key_size: "384"

k8s_controller_manager_csr_key_algo: "ecdsa"
k8s_controller_manager_csr_key_size: "384"

k8s_scheduler_csr_key_algo: "ecdsa"
k8s_scheduler_csr_key_size: "384"

k8s_controller_manager_sa_csr_cn: "k8s-service-accounts"
k8s_controller_manager_sa_csr_key_algo: "ecdsa"
k8s_controller_manager_sa_csr_key_size: "384"

k8s_kube_proxy_csr_key_algo: "ecdsa"
k8s_kube_proxy_csr_key_size: "384"
